### ISSUE TITLE
Player detail pages do not reflect colors in config.yml

### ISSUE THREAD

**Issue by SlimeDog** [Rsl1122/Plan-PlayerAnalytics#101]
**Plan Version:** 3.2.1
**Server Version:** Spigot-1.11.2
**Database Type:** sqlite

**Description:**
Player detail pages do not reflect colors in config.yml

**Steps to Reproduce:**

1. Change color schema in config.yml, for example:
```
Customization:
  Colors:
    Commands:
      Main: '&2'
      Secondary: '&7'
      Highlight: '&f'
    HTML:
      UI:
        Main: '333333'
        MainDark: '666666'
        Secondary: cccccc
        Tertiary: '666666'
        TertiaryDark: cccccc
      ActivityGraph:
        OnlinePlayers: 1E90FF
        OnlinePlayersFill: 75BBFF
        NewPlayers: 228B22
      GamemodePie:
        Survival: '333333'
        Creative: '666666'
        Adventure: '999999'
        Spectator: cccccc
      ActivityPie:
        Active: '333333'
        Banned: '951800'
        Inactive: '666666'
        JoinedOnce: '999999'
```
2. Display player detail page, for example:
> http://myserver.com:8804/OBFUSCATE/player/playerName

Color schema is respected by Server pages.
