### ISSUE TITLE
Option to hide individual player analytic statistics.

### ISSUE THREAD

**Issue by mibby** [Rsl1122/Plan-PlayerAnalytics#161]
Plan v3.5 release build.

Would it be possible to implement a configuration to toggle individual player statistics from being shown? Such as if you would like to outright remove the player kills / mob kills / death display, the age/gender display, the IP, last 10 kills, etc. information graphs.

As with the various tracker listeners disabled, the 'empty' data is still shown in the display. It isn't entirely hidden.
```
  Data:
    GatherLocations: false
    ChatListener: false
    GatherKillData: false
    GamemodeChangeListener: false
    GatherCommandUsage: false
```
