### ISSUE TITLE
Datetime formats

### ISSUE THREAD

**Issue by SlimeDog** [Rsl1122/Plan-PlayerAnalytics#334]
PLAN 4.0.1

It would be nice if datetimes were formatted according to the time formats in config.yml, and aligned right when appropriate. Examples include:
- Information:Averages:SessionLength
- Information:Total:Playtime
- Sessions:50 Most Recent...:Length
- Playerlist:Playtime

**Comment by Rsl1122** [comment]
What do you mean?

**Comment by SlimeDog** [comment]
Current output:
```

Player  | Started       | Length     | World - Time
------- | ------------- | ---------- | ------------
rambeau | Oct 04, 08:42 | 2h 4m 28s  | world_blackdog (99.87%)
rambeau | Oct 04, 08:00 | 3m 31s     | world_blackdog (100%)
rambeau | Oct 03, 16:41 | 27m 52s    | world_blackdog (100%)
rambeau | Oct 03, 13:05 | 3h 17m 28s | world_yellowdog (93.71%)
```
I would like:
```
Player  | Started       | Length   | World - Time
------- | ------------- | -------- | ------------
rambeau | Oct 04, 08:42 |  2:04:28 | world_blackdog (99.87%)
rambeau | Oct 04, 08:00 |    03:31 | world_blackdog (100%)
rambeau | Oct 03, 16:41 |    27:52 | world_blackdog (100%)
rambeau | Oct 03, 13:05 |  3:17:28 | world_yellowdog (93.71%)
```
per the configuration:
```
Customization:
  UseServerTime: true
  Formatting:
    DecimalPoints: '#.##'
    TimeAmount:
      Year: '1 year, '
      Years: '%years% years, '
      Month: '1 month, '
      Months: '%months% months, '
      Day: '1 day '
      Days: '%days% days '
      Hours: '%hours%:'
      Minutes: '%zero%%minutes%:'
      Seconds: '%zero%%seconds%'
```
