### ISSUE TITLE
Feature Request: Sort worldPie by descending time percentage

### ISSUE THREAD

**Issue by SlimeDog** [Rsl1122/Plan-PlayerAnalytics#377]
Very happy about [#333](https://github.com/Rsl1122/Plan-PlayerAnalytics/issues/333) sorting alphabetically. 

At some point, would like the option to sort by percentage of time (descending). Not the highest priority. :)

**Comment by Rsl1122** [comment]
Marked complexity as Medium because sorting by percentage would make world colors inconsistent between different pies, something the original issue solved.

**Comment by SlimeDog** [comment]
True, but if I select that option, I pay that price. :)

**Comment by SlimeDog** [comment]
Plan 4.0.4 with aliases
```
Customization:
...
  WorldAliases:
    world: world
    world_blackdog: blackdog
    world_blackdog_nether: blackdog_nether
    world_blackdog_the_end: blackdog_the_end
    world_city: city
    world_city_nether: city_nether
    world_city_the_end: city_the_end
    world_lobby: lobby
    world_luckyblock: luckyblock
    world_minigames: minigames
    world_nether: nether
    world_skyblock: skyblock
    world_skyblock_nether: skyblock_nether
    world_skyblock_the_end: skyblock_the_end
    world_supreme: supreme
    world_the_end: the_end
    world_void: void
    world_whitedog: whitedog
    world_whitedog_nether: whitedog_nether
    world_whitedog_the_end: whitedog_the_end
    world_yellowdog: yellowdog
    world_yellowdog_nether: yellowdog_nether
    world_yellowdog_the_end: yellowdog_the_end
```
yields
![untitled](https://user-images.githubusercontent.com/17748923/32255657-05522dda-be67-11e7-97b3-42204489ad68.png)

So instead of just shorter world names, worlds without activity are elided from the pie and the legend. This defeats my color scheme (which is illustrated above).

**Comment by SlimeDog** [comment]
Suppose configuration looked something like this:
```
...
WorldGroups:
  BlackDog:
    graphColor: "#DF8CA5"
    worlds:
    - world_blackdog
    - world_blackdog_nether
    - world_blackdog_the_end
  City:
    graphColor: "#66AA66"
    worlds:
    - world_city
    - world_city_nether
    - world_city_the_end
  WhiteDog:
    graphColor: "#66B3DA"
    worlds:
    - world_whitedog
    - world_whitedog_nether
    - world_whitedog_the_end
  YellowDog:
    graphColor: "#F2C331"
    worlds:
    - world_yellowdog
    - world_yellowdog_nether
    - world_yellowdog_the_end
  creative:
    graphColor: "#404447"
    worlds:
    - world
    - world_nether
    - world_the_end
...
```
Then all the data to retain colors would be available, regardless of sort order. Would that work?
