### ISSUE TITLE
World aliases do not work as expected

### ISSUE THREAD

**Issue by SlimeDog** [Rsl1122/Plan-PlayerAnalytics#401]
Spigot 1.12.2 latest
Plan 4.0.4

Without aliases, worldPie is displayed as
![untitled](https://user-images.githubusercontent.com/17748923/32232620-afb06942-be15-11e7-8b0e-f434869e7693.png)

With aliases (below), worldPie is displayed as
![untitled](https://user-images.githubusercontent.com/17748923/32255657-05522dda-be67-11e7-97b3-42204489ad68.png)

```
Customization:
...
  WorldAliases:
    world: world
    world_blackdog: blackdog
    world_blackdog_nether: blackdog_nether
    world_blackdog_the_end: blackdog_the_end
    world_city: city
    world_city_nether: city_nether
    world_city_the_end: city_the_end
    world_lobby: lobby
    world_luckyblock: luckyblock
    world_minigames: minigames
    world_nether: world_nether
    world_skyblock: skyblock
    world_skyblock_nether: skyblock_nether
    world_skyblock_the_end: skyblock_the_end
    world_supreme: supreme
    world_the_end: world_the_end
    world_void: void
    world_whitedog: whitedog
    world_whitedog_nether: whitedog_nether
    world_whitedog_the_end: whitedog_the_end
    world_yellowdog: yellowdog
    world_yellowdog_nether: yellowdog_nether
    world_yellowdog_the_end: yellowdog_the_end
```
So instead of just shorter world names, worlds without activity are elided from the pie and the legend. This defeats my color scheme (which is illustrated above).
