### ISSUE TITLE
[4.0.6-DEV1] String list items are copied

### ISSUE THREAD

**Issue by Rsl1122** [Rsl1122/Plan-PlayerAnalytics#419]
Before reload:
```
Plugins:
    Factions:
        HideFactions:
            - ExampleFaction
    Towny:
        HideTowns:
            - ExampleTown
```
After reload
```
Plugins:
    Factions:
        HideFactions:
            - ExampleFaction
            - ExampleFaction
    Towny:
        HideTowns:
            - ExampleTown
            - ExampleTown
```
```
Plugins:
    Factions:
        HideFactions:
            - ExampleFaction
            - ExampleFaction
            - ExampleFaction
    Towny:
        HideTowns:
            - ExampleTown
            - ExampleTown
            - ExampleTown
```
