### ISSUE TITLE
Improvements to various components related to Play Activity

### ISSUE THREAD

**Issue by sgort87** [Rsl1122/Plan-PlayerAnalytics#460]
I have a number of players who have maxed out their activity at 5. I'd be interested in extending past that cap, if possible. Maybe keep 5 as what it is, but extend the cap to 10.

I'd also like to be able to view player average activity as a ratio to their online time, possibly with adjustable time frames.

Another thing I'd be interested in seeing is separating activity triggers out, to get around false triggers like afk mining at a cobble gen (unless this is already accounted for by checking player position... which I think should also be added if it isn't).

I very much appreciate all the great work you've put into this. I love it! :D
- Gort

**Comment by Rsl1122** [comment]
Under Analysis in the config.yml you can change the requirements for activity index.
The default values were calibrated with data of ~190 players so it might not be super accurate for every server.
```
Analysis:
  AutoRefreshPeriod: 60
  Active:
    # Minutes a player should play per week to be considered active
    PlaytimeThreshold: 30
    # How many days player should join per week to be considered active
    LoginThreshold: 2
```

Players with a 5 have played over 4 times the PlaytimeThreshold every week of the last 3 weeks.
You can probably check their 7 day playtime to calibrate the settings. (In Overview tab of Inspect page)

The number is more forgiving to new players and players who have a break from the game & is mainly affected by coming on the server regularly.
If you're interested in the calculation it is here:
https://github.com/Rsl1122/Plan-PlayerAnalytics/blob/master/Plan/src/main/java/com/djrapitops/plan/data/PlayerProfile.java#L83

How it could be improved is by adding day logins (Say Logged in 2/7 days per week)
I still think it's a good upgrade from just checking if a player joined in the last 2 weeks or not :)
----
Could you elaborate a bit more on that average activity as a ratio to their online time thing?

Afk time will be added at some point when I have the time.
