### ISSUE TITLE
Ping values higher than expected

### ISSUE THREAD

**Issue by SlimeDog** [Rsl1122/Plan-PlayerAnalytics#699]
Spigot 1.13 latest
Plan 4.4.4 (and previous)

Now that I have the ping delays configured, I am still confused about the ping values reported by Plan. 
```
Data:
    # How many minutes player has to stay still to be considered AFK
    AFKThresholdMinutes: 5
    Commands:
        LogUnknownCommands: false
        CombineCommandAliases: true
    Geolocations: true
    Ping:
        ServerEnableDelaySeconds: 300
        PlayerLoginDelaySeconds: 120
    KeepInactivePlayerDataForDays: 180
```
I am the only player on my test server. I have a very fast connection, and my server is approximately 30 miles from my house. Both _ping_ shell command and MC client server list popup report ping values of 23-27ms.
![untitled](https://user-images.githubusercontent.com/17748923/44540907-356a7880-a6bd-11e8-8947-bda2ec275a63.png)
```
64 bytes from IP_ADDRESS_ELIDED: icmp_seq=0 ttl=55 time=24.176 ms
64 bytes from IP_ADDRESS_ELIDED: icmp_seq=1 ttl=55 time=24.147 ms
64 bytes from IP_ADDRESS_ELIDED: icmp_seq=2 ttl=55 time=23.287 ms
64 bytes from IP_ADDRESS_ELIDED: icmp_seq=3 ttl=55 time=23.670 ms
64 bytes from IP_ADDRESS_ELIDED: icmp_seq=4 ttl=55 time=26.481 ms
64 bytes from IP_ADDRESS_ELIDED: icmp_seq=5 ttl=55 time=23.360 ms
64 bytes from IP_ADDRESS_ELIDED: icmp_seq=6 ttl=55 time=22.988 ms
64 bytes from IP_ADDRESS_ELIDED: icmp_seq=7 ttl=55 time=24.310 ms
64 bytes from IP_ADDRESS_ELIDED: icmp_seq=8 ttl=55 time=24.140 ms
64 bytes from IP_ADDRESS_ELIDED: icmp_seq=9 ttl=55 time=23.592 ms
64 bytes from IP_ADDRESS_ELIDED: icmp_seq=10 ttl=55 time=24.122 ms
round-trip min/avg/max/stddev = 23.854/24.561/26.320/0.819 ms
```
Plan reports much higher values, basically double the externally-reported values.
```
sql> select count(*) "n(pings)",
>           min(min_ping) "min(ping)",
>           round(avg(avg_ping),2) "avg(ping)",
>           max(max_ping) "max(ping)"
> from      plan_ping
> where     id>787
> ;
n(pings)    min(ping)   avg(ping)   max(ping) 
----------  ----------  ----------  ----------
150         39          47.35       75
```
Happy to test further if more data are needed.
