### ISSUE TITLE
Time span of one minute gets rendered incorrectly

### ISSUE THREAD

**Issue by BrainStone** [Rsl1122/Plan-PlayerAnalytics#710]
### Describe the bug

With the example given in the wiki:

```yml
      Hours: '%zero%%hours%:'
      Minutes: '%hours%%zero%%minutes%:'
      Seconds: '%minutes%%zero%%seconds%'
      Zero: '00:00:00'
```

The time span 1 second gets rendered as `00:01:` instead of `00:00:01`. Not sure if it affects other 

### Server information

**Plan Version:** 4.4.5
**Server:** BungeeCord git:Waterfall-Bootstrap:1.12-SNAPSHOT:dd9c358:178 git:Waterfall-Bootstrap:1.12-SNAPSHOT:dd9c358:178
**Database:** MySQL

**Operating SubSystem:** Linux (amd64) version 4.9.0-8-amd64
**Java Version:** 1.8.0_171, Oracle Corporation
**Java VM Version:** OpenJDK 64-Bit Server VM version 25.171-b11, Oracle Corporation
**Java VM Flags:** [-Xms921M, -Xmx1843M, -XX:+UseG1GC, -XX:+UnlockExperimentalVMOptions, -XX:MaxGCPauseMillis=100, -XX:+DisableExplicitGC, -XX:TargetSurvivorRatio=90, -XX:G1NeuSizePercent=50, -XX:G1MaxNeuSizePercent=80, -XX:InitiatingHeapOccupancyPercent=10, -XX:G1MixedGCLiveThresholdPercent=50, -XX:+AggressiveOpts, -XX:+AlwaysPreTouch]
