### ISSUE TITLE
Deleted export /server/index.html, cant re-generate it.

### ISSUE THREAD

**Issue by FrozenBeard** [Rsl1122/Plan-PlayerAnalytics#905]
Ahoy!

I setup some other staff users able to access my analytics and then noticed there was some information I didnt want them to see, so I removed this from the settings file, reloaded the plugin and run /plan analyze (To generate the files?) I have /plan analyze run on a cronjob twice a day to run for my export folder as I have the internal web-server disabled. Is this still the right method?

Either way, I deleted my /server/index.html file and now it wont re-generate as when I removed the setting from the config it didn't update the main web UI.

**Comment by Rsl1122** [comment]
Plan analyze is still the command that should perform the file export.

Here are the settings for export that were used during testing
```
Export:
    HTML_Export_path: 'Analysis Results'
    JSON_Export_path: 'Raw JSON'
    Parts:
        JavaScript_and_CSS: true
        Player_pages: true
        Players_page: true
        Server_page: true
        Player_JSON: false
        Server_JSON: false
```

Do your settings match?
